### ISSUE TITLE
Change CheckIn copy to tell people respond by Monday 8am PST

### ISSUE THREAD

**Issue by paked** [hackclub/api#150]
Currently we tell people they need to respond to Hackbot by Monday 8am their local time. Now that we're instituting a hard 8am cut-off time, we should be more accurate as to when people have to respond by.

Actionable: Change CheckIn copy to tell people respond by Monday 8am PST

**Comment by paked** [comment]
@MaxWofford interested in taking this?

**Comment by MaxWofford** [comment]
@paked Just checked this out in https://github.com/hackclub/api/blob/master/app/models/hackbot/interactions/check_in.rb#L164-L172. Aren't we already telling them the check-in closes at their local equivalent of 8 AM PST?

**Comment by MaxWofford** [comment]
Going to close this for now. Please reopen if I missed something.
