### ISSUE TITLE
Hackbot not asking if you had a meeting or not

### ISSUE THREAD

**Issue by metmets** [hackclub/api#153]
Hello! 
Here's a better explanation: 
![screenshot_52](https://cloud.githubusercontent.com/assets/15845246/24075926/2e3b67fc-0c2e-11e7-9910-53f4a7ae5ef4.png)

It doesn't ask if you had a meeting or not. 
(or is this supposed to be a feature?)

**Comment by MaxWofford** [comment]
https://github.com/hackclub/api/pull/147

Fixed!
