### ISSUE TITLE
Use https://papertrail.com instead of Heroku's embedded Papertrail service

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#155]
We're currently using the [Papertrail Heroku addon](https://elements.heroku.com/addons/papertrail) for our logs, which is significantly more expensive than the service available directly from https://papertrail.com – 8GB of logs on https://papertrail.com is $75/m, where 10GB of logs from the Heroku addon is $425/m.

Our primary hosting expense today is Papertrail and as part of our cost cutting, we want to move our logs to the service directly available on https://papertrail.com.

This issue can be resolved once all Heroku applications on the `hackclub` team are using the service available directly from https://papertrail.com. Ping me on Slack if you need billing info.

**Comment by lachlanjc** [comment]
Do we still need to do this?

**Comment by lachlanjc** [comment]
Heroku Papertrail is no longer being used
