### ISSUE TITLE
Assign clubs, leaders, letters, and tasks to their appropriate Hack Club staff member

### ISSUE THREAD

**Issue by paked** [hackclub/api#159]
Currently when any of these `Streakable` items are created they are assigned to API User. This has worked OK up until now, but now that both Max and I are working it is becoming annoying to have to constantly assign these items to each other to various boxes -- and when this 'system' breaks down, it becomes difficult to tell who belongs to who.

So, instead of having humans do things (boo) we should make robots to do them instead (yay!). Whenever a box (of type club, letter, leader OR a task) is created they should be assigned to someone by the following strategies:

- Clubs: Randomly assign between @MaxWofford and I
- Letters: Use leader's assignee
- Leaders: Use club's assignee
- Tasks: Use leader's assignee

**Comment by MaxWofford** [comment]
Nope! Closing
