### ISSUE TITLE
Graphs being generated by Hackbot are incorrect

### ISSUE THREAD

**Issue by paked** [hackclub/api#163]
Just started getting reports from leaders who are now receiving the same graph as the did last week during check ins.

**From @margobra8**

This week:

![image uploaded from ios](https://cloud.githubusercontent.com/assets/8407370/24315420/2aa0298c-10a4-11e7-8f0d-b41578f16766.jpg)

Last week:

![image uploaded from ios-1](https://cloud.githubusercontent.com/assets/8407370/24315428/392e44c0-10a4-11e7-98dc-f55df85aa6aa.jpg)

**Comment by MaxWofford** [comment]
Looks like this is the first 4 check-ins of the leader. I think the fix is to switch `ASC` to `DESC` in https://github.com/hackclub/api/blob/master/app/services/stats_service.rb#L8.

**Comment by MaxWofford** [comment]
Think this would do it:

![screenshot_2017-03-27_20 11 43](https://cloud.githubusercontent.com/assets/5891442/24387385/a59cf728-1329-11e7-8132-9d68a00eb4c3.png)

**Comment by paked** [comment]
👍
