### ISSUE TITLE
Feature request: tie club leader assignee to club assignee

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#17]
If I change the assignee of a club, I'd like the backend to change the assignee of all of the leaders to the club's assignee.

If I change the assignee of a leader, I'd like the backend to change it back to the club's assignee and send me a notification letting me know that if I want to change a leader's assignee, I need to change the club's assignee directly.

**Comment by lachlanjc** [comment]
Afaik not relevant anymore, closing
