### ISSUE TITLE
Hackbot should only send accountability updates on week days

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#171]
It's currently Saturday and Hackbot sent an accountability update to #meta:

<img width="1553" alt="screen shot 2017-09-09 at 15 12 15" src="https://user-images.githubusercontent.com/992248/30244363-56db7f9a-9571-11e7-8eb6-955985437372.png">

Since we're only holding ourselves to these updates on week days, I think Hackbot should only automatically send them on week days.

For this issue to be closed, Hackbot needs to be updated to only send accountability updates Monday - Friday.

**Comment by lachlanjc** [comment]
We can close this
