### ISSUE TITLE
Delete "user left" notifications from #lobby

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#204]
The so and so "left" the channel messages aren't currently deleted by @prophetorpheus.

Demo: https://youtu.be/n0B2lmgX81I?t=2m10s

**Comment by MaxWofford** [comment]
https://www.youtube.com/watch?v=n0B2lmgX81I&feature=youtu.be&t=3m42s

**Comment by zachlatta** [comment]
^ that's the correct timestamp to see the issue.

**Comment by lachlanjc** [comment]
We don't have a lobby channel now, I don't think this is relevant anymore
