### ISSUE TITLE
Leader assignee should be set in the database

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/api#210]
A leader's Streak assignee should be query-able. Without it we can't show who is assigned to leaders  in things like https://modeanalytics.com/hackclub/reports/ef2742373cb6

**Comment by kellywerner** [comment]
@MaxWofford can you share the content publicly? Right now it's password protected.

**Comment by MaxWofford** [comment]
Thinking about it now this issue requires a bunch of context and setup, so I'm removing the `Hacktoberfest` label.

@kellywerner: If you're interested in contributing, check out https://github.com/hackclub/monolith/issues/151.
