### ISSUE TITLE
Simplify Cloud9 sign up process

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/api#217]
Was just on a call with @AppIns and talked about how the set up steps in personal_website took too long. A big chunk of effort and time is the steps to sign up for Cloud9 (esp. when it asks for a credit card https://github.com/hackclub/hackclub/issues/1054).

We can make this easier for people going through the workshop by having a similar sign up form to our Slack sign up form.

**Comment by lachlanjc** [comment]
Has this been done?

**Comment by lachlanjc** [comment]
We can close this since we've migrated to repl.it
