### ISSUE TITLE
Refactor Hackbot::Conversation

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#25]
- State machine should be decoupled from underlying `Conversation` model
- Should support any sort of generic event from Slack (reactions, handling new channels, etc)
- Should allow declared conversations to use something akin to concerns to declare properties – for example, instead of having to inherit from `Hackbot::Conversations::Channel`, I should be able to include that as a concern/mixin (that way, we could do the functional equivalent of multiple inheritance)
- Include a mechanism for decoupling text from the conversation class

**Comment by paked** [comment]
Fixed in #136
