### ISSUE TITLE
NameError: uninitialized constant SlackClient

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#28]
https://sentry.io/hack-club/api/issues/199607216/

```
NameError: uninitialized constant SlackClient
  app/controllers/v1/hackbot/auth_controller.rb:8:in `create'
    resp = ::SlackClient::Oauth.access(CLIENT_ID, CLIENT_SECRET, code)
...
(52 additional frame(s) were not displayed)

NameError: uninitialized constant SlackClient
```

I suspect this has to do with autoloading's behavior in Rails production.

**Comment by MaxWofford** [comment]
Closing this as part of our "Sentry Bankruptcy" -- we've gotten behind on Sentry issues so instead of fixing them retroactively we'll be closing them all and giving any new caught issues top priority.
