### ISSUE TITLE
Refactor /cloud9/invite to use a model

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#41]
Currently `V1::Cloud9Controller` directly POSTs data to Cloud9's API to invite members to Hack Club. This should be refactored to create a `Cloud9Invite` record (and the record should contain the email validation using `EmailValidator`).

**Comment by zachlatta** [comment]
Make sure to properly test this. You can use our code for tech domain redemptions as a general guideline.

**Comment by paked** [comment]
Closed by #198
