### ISSUE TITLE
Handle case where a leader doesn't respond to a check-in

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#45]
Currently `Hackbot::Conversations::CheckIn` doesn't do anything if a leader fails to respond.

We should implement some sort of timeout and follow-up mechanism to handle when this happens. We should also be reflecting when this happens in the check-in conversation's record in the DB.

Just a quick note: I'm currently manually handling failed check-ins and I'm setting `failed_to_complete` to `true` in the `data` attribute for check-ins I'm manually marking as failed.

**Comment by paked** [comment]
Fixed in #103.
