### ISSUE TITLE
AWS SES Upgrade to Signature Version 4

### ISSUE THREAD

**Issue by garyhtou** [hackclub/api#459]
from logs:

> WARN: Net: :SMTPAuthenticationError: 535 Signature Version 2 is deprecated for use with SES from March 26, 2021. From that date on, we are progressively rejecting such requests. To resolve the issue, you must migrate to Signature Version 4. If you created your SMTP credentials in the SES Console, please create new credentials and replace the former ones. If you are deriving Signature Version 2 credentials from a IAM user, please start using the Signature Version 4 algorithm: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html

**Comment by maxwofford** [comment]
Was just on a call with @albertchae. We followed the steps to create a new SMTP user on AWS, and rolled over the credentials on Heroku. Testing it sent a login email successfully, and logs show the new user was being used:
<img width="1207" alt="Screen Shot 2022-04-28 at 15 44 56" src="https://user-images.githubusercontent.com/5891442/165833495-22c18b90-707b-4737-bddb-4788087ecc15.png">
[api-hackclub-smtp-ses](https://us-east-1.console.aws.amazon.com/iam/home#/users/api-hackclub-smtp-ses)


The old user, `api-hackclub-smtp-ses` is still open in case we need to roll back, but let's delete it once we close this ticket. I'm going to set a reminder for myself to close this out next week, after we've had sometime to see if any user reports come in.

**Comment by maxwofford** [comment]
It's been a week and we haven't had any reports from users about this, so I'm going ahead with closing it. We can re-open if it pops up again.
