### ISSUE TITLE
Consolidate stats services

### ISSUE THREAD

**Issue by paked** [hackclub/api#49]
A big part of the work which has been done on Hack Club over the past couple of months has been making it easier for us to collect statistics on things. While this has been a positive change for external forces, the way everything has been implemented internally is... well, it's shit. We're at a point where we have upwards of 3 different statistics related 'services' in our API codebase. Each serving a similar role, calculating the same things in different ways, and all around just not being consistent.

I'd like to consolidate `CheckInReportService`, `ClubStatsService`, and `StatsService` into a single 'Stats' service. With a consistent API.

**Comment by lachlanjc** [comment]
Not using any of these services now afaik
