### ISSUE TITLE
Leaders should be tracked by Slack ID, not Slack username

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/api#65]
We're having issues because Slack usernames are being tracked instead of Slack IDs, and users are changing their usernames.

This involves:

- [ ] adding a stack_id field to the leaders model
- [ ] adding a slack_id field to Streak

**Comment by zachlatta** [comment]
Replaces #22. @paked and I talked offline about the implementation for this. Here's the game plan:

1.  Create new field on Streak for Slack user ID
2.  Set up Leader model to automatically update user ID when username is set and vice versa
3.  Create migration to set user IDs for all previously existing users
4.  Update logic that depends on username and user user ID instead

**Comment by zachlatta** [comment]
Game plan will replace original body by @MaxWofford for this issue.

**Comment by paked** [comment]
Closed by #94
