### ISSUE TITLE
Improve copy of check-in command to be more exciting (GIFs, etc)

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#84]
Here are the notes on the implementation of this that @paked and I put together offline.

1.  Abstract text for responses into YAML files

      ```
	Example format (notice the templating):

		greeting: Hello <%= first_name %>! I am Hackbot.
		first_response:
		 - Whew! That was a really great response
		 - Wow! I am impressed by your skillz.
		attendance_response:
		 good: Wow!
		 great:
		 - Super!
		 - Incredible!
		 - You're the best!
		 best: You're actually the best! I'm so impressed
		goodbye:
		 - See ya!
		 - Bye now!
		 - Good to talk <%= full_name %>!
      ```

2.  Write creative copy for each command
3.  ??? GIFS ???
4.  Profit

Just a quick note on YAML implementation:

- If a key only has one value, then respond with that value
- If a key has multiple values, it should automatically choose one at random

We also spoke about how complex message types might work with this (attachments, message buttons, etc) and decided to defer implementation of those to a later date. In all likelihood, we'll end up coming up with a message schema for complex messages that can be reflected in the YAML.

**Comment by MaxWofford** [comment]
@paked I've just tested everything but the check-in model on a test bot, and reviewed the check-in model by eye. LGTM.

**Comment by MaxWofford** [comment]
Just tested check-ins. Great work!

![](https://media.giphy.com/media/3oz8xKQ7rgHu3dIdUI/giphy.gif)
