### ISSUE TITLE
Implement attendance charts post-check-in and "hackbot stats" command

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#86]
Here are the notes from the conversation that @paked and I had offline about implementing this:

Potential stats:

1.  Club attendance over time compared with target average
2.  Comparison to other clubs nearby (maybe within 10 mile radius, 100 mile radius, etc)
3.  What # person you were to respond to Hackbot
4.  How many meetings you've had so far
5.  How long you've been alive for
6.  How many weeks you had meetings
7.  Your average club attendance
8.  How far away you are from the closest ice cream store
9.  Average club attendance over time
10.  Current overall average club size

End of check-in: Hackbot sends a plot of the past 3 months of meetings compared with the target average for other clubs (target average defined by clubs with average size >10).

Plain ol' Hackbot stats command:

	harrison> hackbot stats
	
	hackbot> Stats on your club:
	
	- Club attendance over time compared with target average
	- Comparison to other clubs nearby within 50 mile radius
	- How many meetings you've had so far
	- How you've been alive for (date of first check-in)
	- Average club attendance

Implementation:

1.  Create CheckInStatsService to generate stats from check-ins
2.  Implement answers to the following questions:
	- Club attendance over time
		- Returns two arrays: one with meeting dates, one with attendance counts – indexes must align
	- Target club attendance over time
		- Target club = club w/ average attendance > 10 members
		- Returns two arrays: one with meeting dates, one with attendance counts – indexes must align
	- Ranking amongst clubs in given radius
		- Calculates average attendances of all clubs within 50 mile radius, then returns ranking # of given club
	- \# of meetings had so far
		- Given a club, returns the # of meetings that have happened so far (be aware of multiple check-ins from different leaders for a single meeting)
	- How long the given club has been alive for
		- Return date of first check-in
	- Average club attendance
		- Returns the average attendance for all meetings of a given club
3.  Implement `hackbot stats` command

**Comment by paked** [comment]
Fixed in #83
