### ISSUE TITLE
Ping people in their timezones (Hackbot check-ins)

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#89]
Here are the notes from the conversation that @paked and I had offline about implementing this:

1.  Create job called ScheduleAndCancelLeaderCheckIns and queue it to run every Thursday
	1.  Cancel CheckIns which were not completed last week.
		1.  Generates Streak tasks for all leaders who did not respond to Hackbot.

			 _Copy for this: "<First Name> didn't respond to the Hackbot check-in this week. Either follow-up with them or mark their club as dead."_ 

	2.  Goes through every point of contact, figures out their timezone using [https://github.com/panthomakos/timezone](https://github.com/panthomakos/timezone) , and then schedules a check-in with them at 5PM local time Friday.

**Comment by paked** [comment]
Fixed in #116
