### ISSUE TITLE
Better onboarding into Hackbot

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#90]
Here are the notes from the conversation @paked and I had offline on how to implement this:

1.  Create WelcomeToSlack conversation which, when triggered (a user joins the Slack) creates a delayed job to send the following text in an hours time

	If not a club leader:

		hackbot> Hey #{name}, super excited you joined the Slack! My name is Hackbot, Hack Club's friendly robot assistant. I hang out on the Slack to help out the staff and our leaders. 
		
		Here's some tricks I know:
		
		- Gifs
		- Definitions
		- Bleh

	If a club leader:

		hackbot> Hey #{name}. Welcome to Hack Club! I'm super excited you're going to be running a club with us at #{school}. My name is Hackbot, Hack Club's friendly robot assistant. I hang out here on the Slack to help out staff and club leaders like you!
		
		Here's some tricks I know:
		
		- Gifs
		- Definitions
		- Bleh

	If a club leader who is the point of contact.

		hackbot>Hey #{name}. Welcome to Hack Club! I'm super excited you're going to be running a club with us at #{school}. My name is Hackbot, Hack Club's friendly robot assistant. I hang out here on the Slack to help out staff and club leaders like you! 
		
		Kyle has told be that you've been nominated as the point of contact for your club, this means that I'll be checking in on you to get some general information every week on Friday at 5pm.
		
		Here's some tricks I know:
		
		- Gifs
		- Definitions
		- Bleh

**Comment by paked** [comment]
This is being worked on in #113.

Some change in scope after a conversation with @kyleemile: Club leaders will be pinged after they fill out the intake form.

I've also rewritten the copy to incorporate some of his ideas.

**Comment by paked** [comment]
Fixed in #155
