### ISSUE TITLE
Give a better name to SLACK_TEAM_ID env var

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#99]
<img width="468" alt="screen shot 2017-03-02 at 11 06 22 am" src="https://cloud.githubusercontent.com/assets/992248/23522600/77c5cc94-ff38-11e6-996a-0b19ad222a70.png">

`SLACK_TEAM_ID` isn't a very descriptive name for this variable because it doesn't tell you what the variable does. Hackbot has functionality built-in to handle multiple Slack teams, does this have something to do with this? Is it something else? This tripped me up when I was trying to set up my dev env.

Perhaps rename it to `DEFAULT_SLACK_TEAM_ID`? That way the name of the variable at least implies that it's the default for something.

**Comment by MaxWofford** [comment]
@zachlatta: I was unaware Hackbot could run on multiple slacks at once. How would one go about setting that up?

**Comment by zachlatta** [comment]
Just login to the hackbot Slack app on multiple Slack teams.
